import * as PDFKit from 'pdfkit';
import * as fs from 'fs';

const PDFDocument = (PDFKit as any).default || PDFKit;

const doc = new PDFDocument({ size: 'LETTER', margin: 40 });
const path = '/Users/a21/gemini-field-assistant/debug-test.pdf';
doc.pipe(fs.createWriteStream(path));

const MARGIN = 40;
const pageWidth = 612 - (MARGIN * 2);

// Header
doc.fontSize(20).fillColor('#1e3a8a').font('Helvetica-Bold')
   .text('STORM DAMAGE HISTORY REPORT', { align: 'center' });
doc.moveDown(0.3);
doc.fontSize(9).fillColor('#64748b').font('Helvetica')
   .text('Report ID: SR-TEST | Generated: 2/2/2026', { align: 'center' });
doc.moveDown(0.5);
doc.moveTo(MARGIN, doc.y).lineTo(612 - MARGIN, doc.y).stroke('#1e3a8a');
doc.moveDown(0.8);

console.log('After header, doc.y =', doc.y);

// Property info
doc.fontSize(12).fillColor('#1e3a8a').font('Helvetica-Bold').text('PROPERTY INFORMATION');
doc.moveDown(0.3);
doc.fontSize(10).fillColor('#1e293b').font('Helvetica');
doc.text('Address: 8100 Boone Blvd, Vienna, VA 22182');
doc.text('Coordinates: 38.92150, -77.23160');
doc.text('Search Radius: 15 miles');
doc.moveDown(0.8);

console.log('After property, doc.y =', doc.y);

// Damage score box
const scoreY = doc.y;
doc.rect(MARGIN, scoreY, pageWidth, 80).fillOpacity(0.08).fill('#eab308').fillOpacity(1);
doc.rect(MARGIN, scoreY, pageWidth, 80).strokeColor('#eab308').lineWidth(2).stroke();
doc.fontSize(42).fillColor('#eab308').font('Helvetica-Bold').text('42', MARGIN + 20, scoreY + 15, { width: 80 });
doc.fontSize(16).fillColor('#eab308').font('Helvetica-Bold').text('MODERATE RISK', MARGIN + 110, scoreY + 20);
doc.y = scoreY + 95;

console.log('After score box, doc.y =', doc.y);

// Summary
doc.fontSize(12).fillColor('#1e3a8a').font('Helvetica-Bold').text('EXECUTIVE SUMMARY');
doc.moveDown(0.3);
doc.fontSize(10).fillColor('#1e293b').font('Helvetica');
doc.text('• Total Storm Events: 3');
doc.text('• Largest Hail Size: 1.3"');
doc.text('• Severe Events: 0');
doc.moveDown(0.8);

console.log('After summary, doc.y =', doc.y);

// Timeline header
doc.fontSize(12).fillColor('#1e3a8a').font('Helvetica-Bold').text('STORM EVENT TIMELINE');
doc.moveDown(0.3);

let tableY = doc.y;
const tableWidth = 400;
doc.rect(MARGIN, tableY, tableWidth, 18).fill('#1e3a8a');
doc.fontSize(8).fillColor('#ffffff').font('Helvetica-Bold').text('Date', MARGIN + 3, tableY + 5);
tableY += 18;

// 3 rows
for (let i = 0; i < 3; i++) {
  if (i % 2 === 0) doc.rect(MARGIN, tableY, tableWidth, 16).fill('#f8fafc');
  doc.rect(MARGIN, tableY, tableWidth, 16).stroke('#e2e8f0');
  doc.fontSize(8).fillColor('#1e293b').font('Helvetica').text(`Jul ${15-i}, 2024`, MARGIN + 3, tableY + 4);
  tableY += 16;
}
doc.y = tableY + 20;

console.log('After timeline, doc.y =', doc.y);

// Evidence
doc.fontSize(12).fillColor('#1e3a8a').font('Helvetica-Bold').text('EVIDENCE FOR INSURANCE CLAIMS');
doc.moveDown(0.3);
doc.fontSize(9).fillColor('#1e293b').font('Helvetica');
doc.text('1. NOAA Storm Events Database - Official U.S. government record.');
doc.text('2. Interactive Hail Maps (IHM) - Professional storm tracking.');
doc.moveDown(0.5);

console.log('After evidence, doc.y =', doc.y);

// Disclaimer
const disclaimerY = doc.y;
doc.rect(MARGIN, disclaimerY, pageWidth, 45).fillOpacity(0.05).fill('#666').fillOpacity(1);
doc.rect(MARGIN, disclaimerY, pageWidth, 45).stroke('#e2e8f0');
doc.fontSize(7).fillColor('#64748b').font('Helvetica-Oblique')
   .text('DISCLAIMER: This report is for informational purposes only.', MARGIN + 8, disclaimerY + 8, { width: pageWidth - 16 });

console.log('After disclaimer, doc.y =', doc.y);

// Footer at bottom
const footerY = 742;
doc.moveTo(MARGIN, footerY).lineTo(612 - MARGIN, footerY).stroke('#e2e8f0');
doc.fontSize(8).fillColor('#64748b').font('Helvetica').text('Generated by SA21', MARGIN, footerY + 5);

doc.end();

setTimeout(() => {
  const stats = fs.statSync(path);
  console.log('File size:', stats.size, 'bytes');
  require('child_process').execSync(`file "${path}"`).toString();
}, 500);
